name = "ExactDiagonalization"
uuid = "cf149b0a-e8f7-4f00-9ab4-03e4f5ec5cff"
authors = ["Kyungmin Lee <kyungmin.lee.42@gmail.com>"]
version = "0.13.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
LatticeTools = "8a267902-5e0e-44c3-8ef8-9b2b5c352816"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = ">= 1.5"

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Suppressor"]
